//KLEUREN SCHEMA DAT GEBRUIKT KAN WORDEN
final int COLOR_WHITE = #FFFFFF;
final int COLOR_BLACK = #000000;
final int COLOR_BLUE = #0000FF;
final int COLOR_RED = #FF0000;
final int COLOR_GREEN = #00FF00;
final int COLOR_GRAY = #808080;
final int COLOR_MAGENTA = #FF00FF;
final int COLOR_PURPLE = #800080;
final int COLOR_GOLD = #FFD700;
final int COLOR_GOLD_PALE = #E6BE8A;
final int COLOR_GOLD_METALLIC = #D4AF37;
